packages:
  - packages/**
  - apps/**

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@heroui/shared-utils'
  - '@tailwindcss/oxide'
  - aws-sdk
  - esbuild
  - msgpackr-extract
