/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AthenaApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "ProExporter": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ProMatchesSeen": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ProSync": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "RiotApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}