/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RewindIdRouteImport } from './routes/rewind/$id'
import { Route as QueueIdRouteImport } from './routes/queue/$id'
import { Route as RegionNameTagRouteImport } from './routes/$region/$name/$tag'
import { Route as RegionNameTagIndexRouteImport } from './routes/$region/$name/$tag/index'
import { Route as RegionNameTagMatchesRouteImport } from './routes/$region/$name/$tag/matches'
import { Route as RegionNameTagChampionsRouteImport } from './routes/$region/$name/$tag/champions'
import { Route as RegionNameTagMatchMatchIdRouteImport } from './routes/$region/$name/$tag/match/$matchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RewindIdRoute = RewindIdRouteImport.update({
  id: '/rewind/$id',
  path: '/rewind/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueIdRoute = QueueIdRouteImport.update({
  id: '/queue/$id',
  path: '/queue/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionNameTagRoute = RegionNameTagRouteImport.update({
  id: '/$region/$name/$tag',
  path: '/$region/$name/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionNameTagIndexRoute = RegionNameTagIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegionNameTagRoute,
} as any)
const RegionNameTagMatchesRoute = RegionNameTagMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => RegionNameTagRoute,
} as any)
const RegionNameTagChampionsRoute = RegionNameTagChampionsRouteImport.update({
  id: '/champions',
  path: '/champions',
  getParentRoute: () => RegionNameTagRoute,
} as any)
const RegionNameTagMatchMatchIdRoute =
  RegionNameTagMatchMatchIdRouteImport.update({
    id: '/match/$matchId',
    path: '/match/$matchId',
    getParentRoute: () => RegionNameTagRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/queue/$id': typeof QueueIdRoute
  '/rewind/$id': typeof RewindIdRoute
  '/$region/$name/$tag': typeof RegionNameTagRouteWithChildren
  '/$region/$name/$tag/champions': typeof RegionNameTagChampionsRoute
  '/$region/$name/$tag/matches': typeof RegionNameTagMatchesRoute
  '/$region/$name/$tag/': typeof RegionNameTagIndexRoute
  '/$region/$name/$tag/match/$matchId': typeof RegionNameTagMatchMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/queue/$id': typeof QueueIdRoute
  '/rewind/$id': typeof RewindIdRoute
  '/$region/$name/$tag/champions': typeof RegionNameTagChampionsRoute
  '/$region/$name/$tag/matches': typeof RegionNameTagMatchesRoute
  '/$region/$name/$tag': typeof RegionNameTagIndexRoute
  '/$region/$name/$tag/match/$matchId': typeof RegionNameTagMatchMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/queue/$id': typeof QueueIdRoute
  '/rewind/$id': typeof RewindIdRoute
  '/$region/$name/$tag': typeof RegionNameTagRouteWithChildren
  '/$region/$name/$tag/champions': typeof RegionNameTagChampionsRoute
  '/$region/$name/$tag/matches': typeof RegionNameTagMatchesRoute
  '/$region/$name/$tag/': typeof RegionNameTagIndexRoute
  '/$region/$name/$tag/match/$matchId': typeof RegionNameTagMatchMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/queue/$id'
    | '/rewind/$id'
    | '/$region/$name/$tag'
    | '/$region/$name/$tag/champions'
    | '/$region/$name/$tag/matches'
    | '/$region/$name/$tag/'
    | '/$region/$name/$tag/match/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/queue/$id'
    | '/rewind/$id'
    | '/$region/$name/$tag/champions'
    | '/$region/$name/$tag/matches'
    | '/$region/$name/$tag'
    | '/$region/$name/$tag/match/$matchId'
  id:
    | '__root__'
    | '/'
    | '/queue/$id'
    | '/rewind/$id'
    | '/$region/$name/$tag'
    | '/$region/$name/$tag/champions'
    | '/$region/$name/$tag/matches'
    | '/$region/$name/$tag/'
    | '/$region/$name/$tag/match/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QueueIdRoute: typeof QueueIdRoute
  RewindIdRoute: typeof RewindIdRoute
  RegionNameTagRoute: typeof RegionNameTagRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewind/$id': {
      id: '/rewind/$id'
      path: '/rewind/$id'
      fullPath: '/rewind/$id'
      preLoaderRoute: typeof RewindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue/$id': {
      id: '/queue/$id'
      path: '/queue/$id'
      fullPath: '/queue/$id'
      preLoaderRoute: typeof QueueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$region/$name/$tag': {
      id: '/$region/$name/$tag'
      path: '/$region/$name/$tag'
      fullPath: '/$region/$name/$tag'
      preLoaderRoute: typeof RegionNameTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$region/$name/$tag/': {
      id: '/$region/$name/$tag/'
      path: '/'
      fullPath: '/$region/$name/$tag/'
      preLoaderRoute: typeof RegionNameTagIndexRouteImport
      parentRoute: typeof RegionNameTagRoute
    }
    '/$region/$name/$tag/matches': {
      id: '/$region/$name/$tag/matches'
      path: '/matches'
      fullPath: '/$region/$name/$tag/matches'
      preLoaderRoute: typeof RegionNameTagMatchesRouteImport
      parentRoute: typeof RegionNameTagRoute
    }
    '/$region/$name/$tag/champions': {
      id: '/$region/$name/$tag/champions'
      path: '/champions'
      fullPath: '/$region/$name/$tag/champions'
      preLoaderRoute: typeof RegionNameTagChampionsRouteImport
      parentRoute: typeof RegionNameTagRoute
    }
    '/$region/$name/$tag/match/$matchId': {
      id: '/$region/$name/$tag/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/$region/$name/$tag/match/$matchId'
      preLoaderRoute: typeof RegionNameTagMatchMatchIdRouteImport
      parentRoute: typeof RegionNameTagRoute
    }
  }
}

interface RegionNameTagRouteChildren {
  RegionNameTagChampionsRoute: typeof RegionNameTagChampionsRoute
  RegionNameTagMatchesRoute: typeof RegionNameTagMatchesRoute
  RegionNameTagIndexRoute: typeof RegionNameTagIndexRoute
  RegionNameTagMatchMatchIdRoute: typeof RegionNameTagMatchMatchIdRoute
}

const RegionNameTagRouteChildren: RegionNameTagRouteChildren = {
  RegionNameTagChampionsRoute: RegionNameTagChampionsRoute,
  RegionNameTagMatchesRoute: RegionNameTagMatchesRoute,
  RegionNameTagIndexRoute: RegionNameTagIndexRoute,
  RegionNameTagMatchMatchIdRoute: RegionNameTagMatchMatchIdRoute,
}

const RegionNameTagRouteWithChildren = RegionNameTagRoute._addFileChildren(
  RegionNameTagRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QueueIdRoute: QueueIdRoute,
  RewindIdRoute: RewindIdRoute,
  RegionNameTagRoute: RegionNameTagRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
