/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RewindIdRouteImport } from './routes/rewind/$id'
import { Route as QueueIdRouteImport } from './routes/queue/$id'
import { Route as RegionNameTagRouteImport } from './routes/$region/$name/$tag'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RewindIdRoute = RewindIdRouteImport.update({
  id: '/rewind/$id',
  path: '/rewind/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueIdRoute = QueueIdRouteImport.update({
  id: '/queue/$id',
  path: '/queue/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionNameTagRoute = RegionNameTagRouteImport.update({
  id: '/$region/$name/$tag',
  path: '/$region/$name/$tag',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/queue/$id': typeof QueueIdRoute
  '/rewind/$id': typeof RewindIdRoute
  '/$region/$name/$tag': typeof RegionNameTagRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/queue/$id': typeof QueueIdRoute
  '/rewind/$id': typeof RewindIdRoute
  '/$region/$name/$tag': typeof RegionNameTagRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/queue/$id': typeof QueueIdRoute
  '/rewind/$id': typeof RewindIdRoute
  '/$region/$name/$tag': typeof RegionNameTagRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/queue/$id' | '/rewind/$id' | '/$region/$name/$tag'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/queue/$id' | '/rewind/$id' | '/$region/$name/$tag'
  id: '__root__' | '/' | '/queue/$id' | '/rewind/$id' | '/$region/$name/$tag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QueueIdRoute: typeof QueueIdRoute
  RewindIdRoute: typeof RewindIdRoute
  RegionNameTagRoute: typeof RegionNameTagRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewind/$id': {
      id: '/rewind/$id'
      path: '/rewind/$id'
      fullPath: '/rewind/$id'
      preLoaderRoute: typeof RewindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue/$id': {
      id: '/queue/$id'
      path: '/queue/$id'
      fullPath: '/queue/$id'
      preLoaderRoute: typeof QueueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$region/$name/$tag': {
      id: '/$region/$name/$tag'
      path: '/$region/$name/$tag'
      fullPath: '/$region/$name/$tag'
      preLoaderRoute: typeof RegionNameTagRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QueueIdRoute: QueueIdRoute,
  RewindIdRoute: RewindIdRoute,
  RegionNameTagRoute: RegionNameTagRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
